name: Default build pipeline

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  packages: write
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Tags
        run: git fetch --unshallow --tags
      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          arguments: build sonar -Preckon.stage=final -Preckon.scope=patch reckonTagCreate
      - name: Push git tag
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          arguments: reckonTagPush
      - name: Deploy artifacts to GitHub Packages
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          arguments: publish
