name: Default build pipeline

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          arguments: build -Preckon.stage=final reckonTagCreate reckonTagPush
      - name: Deploy artifacts to GitHub Packages
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          arguments: publish
